apiVersion: v1
kind: Pod
metadata:
  name: bad-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox:error-tag
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']