apiVersion: v1
kind: Pod
metadata:
  name: work-demo
spec:
  volumes:
  - name: data
    emptyDir: {}
    
  initContainers:
  - name: init-1
    image: busybox
    command: [ "sh", "-c", "echo start 1 >> /data/file" ]
    volumeMounts:
    - name: data
      mountPath: /data
  containers:
  
  - name: goproxy
    image: googlecontainer/goproxy:0.1
    volumeMounts:
    - name: data
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20

  - name: debian-container
    image: debian
    volumeMounts:
    - name: data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from the debian container > /pod-data/index.html"]
    resources:
      requests: 
        memory: "200Mi"
        cpu: "500m"
      limits: 
        memory: "200Mi"
        cpu: "500m"