global:


route:
  group_wait: 1s
  group_interval: 1s
  receiver: shiyanlou
  routes:
  - match:
      job: nginx
	group_by: ['job']
	receiver: shiyanlou

receivers:
- name: shiyanlou
  webhook_configs:
  - url: http://localhost:8000/