services:
  # set redis service
  redis:
    image: redis:3.2
  # set web service
  web:
    image: app_web:latest
    depends_on:
    - redis
    ports:
    - 8001:80/tcp
    volumes:
    - /home/shiyanlou/app/web:/web:rw
version: '3.0'