apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-work
  labels:
    app: nginx-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # 设置类似DemonSet的结点功能
      nodeSelector:
        app: nginx-node
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
